### ISSUE TITLE
Add package on Gentoo

### ISSUE THREAD

**Issue by ghost** [Sayrus/msi-keyboard#1]
Hello, thanks you for your works. I have just one question, can you had this repository officially for Gentoo please ? On Gentoo, there aren't any repository for control my MSI keyboard backlight :C

**Comment by Sayrus** [comment]
Hello Zohran,

I'll look into how the Gentoo Build system works and how you can upload private ebuilds.
If you already know the way or have already created a package for Gentoo, feel free to give me useful documentation/tips about that.

**Comment by ghost** [comment]
Hello :)

I have posted on Gentoo forum to add more informations about Gentoo ebuild, if you like more documentation, read replys on this topic: https://forums.gentoo.org/viewtopic-t-1072284-highlight-.html

And this link: https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers

Thanks again for your work :)
